// Code generated by Prismic. DO NOT EDIT.
// Deviation: static imports, not `dynamic()`. See scripts/README.md.

import About from './About'
import ArtistList from './ArtistList'
import Contact from './Contact'
import Donate from './Donate'
import EventList from './EventList'
import Hero from './Hero'
import LegalSection from './LegalSection'
import Quote from './Quote'
import RichText from './RichText'
import Sponsors from './Sponsors'
import Volunteers from './Volunteers'

export const components = {
  about: About,
  artist_list: ArtistList,
  contact: Contact,
  donate: Donate,
  event_list: EventList,
  hero: Hero,
  legal_section: LegalSection,
  quote: Quote,
  rich_text: RichText,
  sponsors: Sponsors,
  volunteers: Volunteers,
}
