// Code generated by Prismic. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
	about: dynamic(() => import("./About")),
	artist_list: dynamic(() => import("./ArtistList")),
	contact: dynamic(() => import("./Contact")),
	donate: dynamic(() => import("./Donate")),
	event_list: dynamic(() => import("./EventList")),
	hero: dynamic(() => import("./Hero")),
	image_gallery: dynamic(() => import("./ImageGallery")),
	quote: dynamic(() => import("./Quote")),
	rich_text: dynamic(() => import("./RichText")),
	sponsors: dynamic(() => import("./Sponsors")),
	volunteers: dynamic(() => import("./Volunteers")),
};
